#ifndef ASSETS_H_INCLUDED
#define ASSETS_H_INCLUDED

#define BACKGROUND_FILENAME "2D/background.png"

#define SHIP_FILENAME		"2D/natalia.png"
#define SHIP_WIDTH			64
#define SHIP_HEIGHT			64
#define SHIP_NB_FRAMES		3

#define PORTAL_TEXTURE_NAME		"2D/World/Portal.png"
#define PORTAL_WIDTH			192
#define PORTAL_HEIGHT			192
#define PORTAL_FRAMES			4
#define PORTAL_ANIMATIONS		4

#define HUD_CURSOR_TEXTURE_NAME			"2D/HUD/cursor.png"
#define HUD_CURSOR_WIDTH				33
#define HUD_CURSOR_HEIGHT				32
#define HUD_CURSOR_HOLDING_FRACTIONS	8

#define	COLOR_GREEN_R_VALUE				148
#define	COLOR_GREEN_G_VALUE				247
#define	COLOR_GREEN_B_VALUE				79
#define	COLOR_GREEN_A_VALUE				128
//COLOR_GREEN_R_VALUE, COLOR_GREEN_G_VALUE, COLOR_GREEN_B_VALUE, COLOR_GREEN_A_VALUE

#define	COLOR_BLUE_R_VALUE				0
#define	COLOR_BLUE_G_VALUE				79
#define	COLOR_BLUE_B_VALUE				157
#define	COLOR_BLUE_A_VALUE				128
//COLOR_BLUE_R_VALUE, COLOR_BLUE_G_VALUE, COLOR_BLUE_B_VALUE, COLOR_BLUE_A_VALUE

#define	COLOR_YELLOW_R_VALUE				255
#define	COLOR_YELLOW_G_VALUE				200
#define	COLOR_YELLOW_B_VALUE				14
#define	COLOR_YELLOW_A_VALUE				128
//COLOR_BLUE_R_VALUE, COLOR_BLUE_G_VALUE, COLOR_BLUE_B_VALUE, COLOR_BLUE_A_VALUE

#define	COLOR_LIGHT_BLUE_R_VALUE		0
#define	COLOR_LIGHT_BLUE_G_VALUE		100
#define	COLOR_LIGHT_BLUE_B_VALUE		200
#define	COLOR_LIGHT_BLUE_A_VALUE		179

//#define AIRBRAKE_FILENAME		"2D/Equipment/AirBrake.png"
#define ARMOR_FILENAME			"2D/Equipment/Armor.png"
#define LASER_RED_FILENAME		"2D/Equipment/laser_red.png"
#define LASER_BLUE_FILENAME		"2D/Equipment/laser_blue1.png"
#define SHIELD_FILENAME			"2D/Equipment/Shield.png"
#define THRUSTER_FILENAME		"2D/Equipment/Thruster.png"
#define MODULE_FILENAME			"2D/Equipment/Module.png"
#define BOT_FILENAME			"2D/Equipment/bot.png"

#define QUALITY_BACKGROUND		"2D/Equipment/quality_background.png"
#define EQUIPMENT_SIZE					48
#define BOT_SIZE						32
#define EMPTYSLOT_FILENAME				"2D/HUD/EmptySlot.png"
#define GRID_SLOT_SIZE					64

#define FX_EXPLOSION_FILENAME				"2D/FX/FX_explosion.png"
#define FX_EXPLOSION_WIDTH					320
#define FX_EXPLOSION_HEIGHT					236
#define FX_EXPLOSION_FRAME_NUMBER			4
#define FX_LITTLE_EXPLOSION_DURATION		0.1f
#define FX_MEDIUM_EXPLOSION_DURATION		0.2f
#define FX_LARGE_EXPLOSION_DURATION			0.8f

#define FX_EXPLOSION_BLUE_FILENAME			"2D/FX/FX_explosion_S_blue.png"
#define FX_EXPLOSION_BLUE_WIDTH				320
#define FX_EXPLOSION_BLUE_HEIGHT			236
#define FX_EXPLOSION_BLUE_FRAME_NUMBER		2
#define FX_EXPLOSION_BLUE_DURATION			0.4f

#define LOOT_FILENAME				"2D/World/crystal.png"
#define LOOT_WIDTH					32
#define LOOT_HEIGHT					32
#define LOOT_SPEED_Y				50.f

//HAZARD BREAK DISPLAY
#define ENDSCENE_SCORE_DISPLAY_POSITION_Y	300

//SHOP
#define SHOP_ASSET_FILENAME					"2D/PNJ/station.png"
#define SHOP_ASSET_WIDTH					319
#define SHOP_ASSET_HEIGHT					158

//ICONS
#define ICON_SHIP_PNG						"Icons/ShipModel_icon.png"

#endif // ASSETS_H_INCLUDED

