# Install script for directory: E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/SFGUI")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/HelloWorld.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/HelloWorld.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/HelloWorld.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/HelloWorld.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/HelloWorld.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/Window.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/Window.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/Window.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/Window.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Window.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/Label.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/Label.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/Label.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/Label.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Label.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/Box.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/Box.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/Box.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/Box.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Box.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/Entry.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/Entry.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/Entry.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/Entry.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Entry.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/Range.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/Range.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/Range.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/Range.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Range.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/Desktop.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/Desktop.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/Desktop.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/Desktop.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Desktop.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/Signals.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/Signals.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/Signals.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/Signals.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Signals.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/OpenGL.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/OpenGL.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/OpenGL.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/OpenGL.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/OpenGL.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/ComboBox.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/ComboBox.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/ComboBox.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/ComboBox.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/ComboBox.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/Notebook.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/Notebook.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/Notebook.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/Notebook.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Notebook.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/GuessMyNumber.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/GuessMyNumber.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/GuessMyNumber.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/GuessMyNumber.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/GuessMyNumber.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/Multiview.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/Multiview.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/Multiview.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/Multiview.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Multiview.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/Image.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/Image.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/Image.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/Image.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Image.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/Layout.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/Layout.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/Layout.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/Layout.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Layout.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/ScrolledWindowViewport.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/ScrolledWindowViewport.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/ScrolledWindowViewport.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/ScrolledWindowViewport.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/ScrolledWindowViewport.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/Spinner.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/Spinner.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/Spinner.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/Spinner.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Spinner.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/Table.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/Table.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/Table.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/Table.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Table.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/Buttons.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/Buttons.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/Buttons.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/Buttons.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Buttons.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/ProgressBar.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/ProgressBar.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/ProgressBar.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/ProgressBar.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/ProgressBar.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/SpinButton.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/SpinButton.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/SpinButton.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/SpinButton.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/SpinButton.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/Canvas.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/Canvas.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/Canvas.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/Canvas.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Canvas.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Debug/test.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Release/test.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/MinSizeRel/test.exe")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE EXECUTABLE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/RelWithDebInfo/test.exe")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "examples")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE FILE FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/Test.cpp")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./examples" TYPE DIRECTORY FILES "E:/s/SFGUI-0.2.0-vs2013/SFGUI-0.2.0/examples/data")
endif()

